# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: socket_data.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class PricingDataQuoteType(betterproto.Enum):
    NONE = 0
    ALTSYMBOL = 5
    HEARTBEAT = 7
    EQUITY = 8
    INDEX = 9
    MUTUALFUND = 11
    MONEYMARKET = 12
    OPTION = 13
    CURRENCY = 14
    WARRANT = 15
    BOND = 17
    FUTURE = 18
    ETF = 20
    COMMODITY = 23
    ECNQUOTE = 28
    CRYPTOCURRENCY = 41
    INDICATOR = 42
    INDUSTRY = 1000


class PricingDataOptionType(betterproto.Enum):
    CALL = 0
    PUT = 1


class PricingDataMarketHoursType(betterproto.Enum):
    PRE_MARKET = 0
    REGULAR_MARKET = 1
    POST_MARKET = 2
    EXTENDED_HOURS_MARKET = 3


@dataclass
class PricingData(betterproto.Message):
    id: str = betterproto.string_field(1)
    price: float = betterproto.float_field(2)
    time: int = betterproto.sint64_field(3)
    currency: str = betterproto.string_field(4)
    exchange: str = betterproto.string_field(5)
    quote_type: "PricingDataQuoteType" = betterproto.enum_field(6)
    market_hours: "PricingDataMarketHoursType" = betterproto.enum_field(7)
    change_percent: float = betterproto.float_field(8)
    day_volume: int = betterproto.sint64_field(9)
    day_high: float = betterproto.float_field(10)
    day_low: float = betterproto.float_field(11)
    change: float = betterproto.float_field(12)
    short_name: str = betterproto.string_field(13)
    expire_date: int = betterproto.sint64_field(14)
    open_price: float = betterproto.float_field(15)
    previous_close: float = betterproto.float_field(16)
    strike_price: float = betterproto.float_field(17)
    underlying_symbol: str = betterproto.string_field(18)
    open_interest: int = betterproto.sint64_field(19)
    options_type: "PricingDataOptionType" = betterproto.enum_field(20)
    mini_option: int = betterproto.sint64_field(21)
    last_size: int = betterproto.sint64_field(22)
    bid: float = betterproto.float_field(23)
    bid_size: int = betterproto.sint64_field(24)
    ask: float = betterproto.float_field(25)
    ask_size: int = betterproto.sint64_field(26)
    price_hint: int = betterproto.sint64_field(27)
    vol_24hr: int = betterproto.sint64_field(28)
    vol_all_currencies: int = betterproto.sint64_field(29)
    fromcurrency: str = betterproto.string_field(30)
    last_market: str = betterproto.string_field(31)
    circulating_supply: float = betterproto.double_field(32)
    marketcap: float = betterproto.double_field(33)
